// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tivqenmrdcuubqrhvsjo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpdnFlbm1yZGN1dWJxcmh2c2pvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NzMzMDAsImV4cCI6MjA2ODQ0OTMwMH0.OAAvGBOHc996fZoGX9P7sNs2uimsyKJ23MCZWr2R8Ho";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});